name: Generate Metrics

on:
  schedule:
    - cron: "* */12 * * *"

jobs:
  metrics-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          filename: metrics.svg

      - name: Upload metrics
        uses: actions/upload-artifact@v2
        with:
          name: metrics
          path: metrics.svg

      - name: Commit and push metrics
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add metrics.svg
          git commit -m "Update metrics"
          git push
